name: fishplacetrack_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^0.13.5
  image_picker: ^0.8.7
  intl: ^0.18.1
  firebase_core: ^2.15.0
  firebase_auth: ^4.9.0
  google_sign_in: ^6.1.0
  shared_preferences: ^2.2.0
  cached_network_image: ^3.3.0
  fluttertoast: ^8.2.2
  google_maps_flutter: ^2.2.3
  url_launcher: ^6.1.10
  share_plus: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
